INCLUDE ~%MOD_FOLDER%/libs/scripts/remedies/fragments/zs_incl_remedies.tph~

PRINT "Distributing remedies to NPCs and stores..."
SILENT

INCLUDE ~%MOD_FOLDER%/libs/scripts/remedies/fragments/zs_incl_remedies_stores.tph~
INCLUDE ~%MOD_FOLDER%/libs/scripts/remedies/fragments/zs_incl_remedies_cre_manual.tph~
INCLUDE ~%MOD_FOLDER%/libs/scripts/remedies/fragments/zs_incl_remedies_cre_auto.tph~

VERBOSE
PRINT "Finished distributing remedies to NPCs and stores."
