COPY_EXISTING ~udphae01.cre~ ~override~ // phaere
              ~udphae02.cre~ ~override~ // phaere
              ~cuphaer.cre~  ~override~ // phaere
              ~udsola01.cre~ ~override~ // solaufein
              ~udsola02.cre~ ~override~ // solaufein
              ~dadrow10.cre~ ~override~ // drow torturer
              ~dadrow11.cre~ ~override~ // drow torturer
              ~dadrow8.cre~  ~override~ // drow torturer
              ~dadrow9.cre~  ~override~ // drow torturer
              ~dadrow6.cre~  ~override~ // drow leader

        SET random = RANDOM(1 3)
        ADD_CRE_ITEM ~zscsweb0~ (random) (0) (0) ~none~ ~inv4 inv5 inv6 inv7 inv8 inv9 inv10 inv11 inv12 inv13 inv14 inv15 inv16~ // web grenade

BUT_ONLY IF_EXISTS
