ACTION_IF NOT GAME_IS "iwdee" BEGIN

    ACTION_IF FILE_EXISTS_IN_GAME ~ppstor01.sto~ BEGIN // storekeep brynnlaw

        COPY_EXISTING ~ppstor01.sto~ ~override~ // storekeep brynnlaw

            PATCH_IF zs_cons_add_angelic_reprieve BEGIN
                LPF resolve_amount INT_VAR chance=20 RET amount END
                LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
            END

        BUT_ONLY

    END

    ACTION_IF FILE_EXISTS_IN_GAME ~trmer02.sto~ BEGIN // MERCHANT TRADEMEET

        COPY_EXISTING ~trmer02.sto~ ~override~ // MERCHANT TRADEMEET

            PATCH_IF zs_cons_add_angelic_reprieve BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(1 3) STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
            END
            PATCH_IF zs_cons_add_angelic_slumber BEGIN
                LPF resolve_amount INT_VAR chance=8 RET amount END
                LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsasl0~ END // angelic slumber
            END

            PATCH_IF zs_cons_add_basilisk_oil BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(2 4) STR_VAR item_name = ~zscsbsk0~ END // basilisk oil
            END

        BUT_ONLY

    END

    ACTION_IF FILE_EXISTS_IN_GAME ~murcrag.sto~ BEGIN // MRS CRAGMOON

        COPY_EXISTING ~murcrag.sto~ ~override~ // MRS CRAGMOON

            PATCH_IF zs_cons_add_angelic_reprieve BEGIN
                LPF resolve_amount INT_VAR chance=33 RET amount END
                LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
            END

            PATCH_IF zs_cons_add_angelic_slumber BEGIN
                LPF resolve_amount INT_VAR chance=8 RET amount END
                LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsasl0~ END // angelic slumber
            END

            PATCH_IF zs_cons_add_basilisk_oil BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(2 4) STR_VAR item_name = ~zscsbsk0~ END // basilisk oil
            END

            PATCH_IF zs_cons_add_remedial_solution BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(3 6) STR_VAR item_name = ~zscsrms0~ END // remedial solution
            END

        BUT_ONLY

    END

    ACTION_IF FILE_EXISTS_IN_GAME ~bhelm.sto~ BEGIN //helm's temple

        COPY_EXISTING ~bhelm.sto~   ~override~ //helm's temple
                      ~temhelm.sto~ ~override~ //helm's temple
                      ~tem4802.sto~ ~override~ //helm's temple

            PATCH_IF zs_cons_add_angelic_reprieve BEGIN
                LPF resolve_amount INT_VAR chance=12 base_amount=2 target_amount = RANDOM(3 4) RET amount END
                LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
            END

            PATCH_IF zs_cons_add_basilisk_oil BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(1 2) STR_VAR item_name = ~zscsbsk0~ END // basilisk oil
            END

            PATCH_IF zs_cons_add_remedial_solution BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM (3 7) STR_VAR item_name = ~zscsrms0~ END // remedial solution
            END

        BUT_ONLY

    END

    ACTION_IF FILE_EXISTS_IN_GAME ~ulgoth.sto~ BEGIN //ulgoth's inn
        COPY_EXISTING ~ulgoth.sto~ ~override~ //helm's temple

            PATCH_IF zs_cons_add_angelic_reprieve BEGIN
                LPF resolve_amount INT_VAR chance=12 base_amount=2 target_amount = 3 RET amount END
                LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
            END

            PATCH_IF zs_cons_add_remedial_solution BEGIN
                LPF resolve_amount INT_VAR chance=10 RET amount END
                LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsrms0~ END // angelic slumber
            END

        BUT_ONLY
    END

    ACTION_IF FILE_EXISTS_IN_GAME ~tem3402.sto~ BEGIN //helm's temple
        COPY_EXISTING ~tem3402.sto~ ~override~ //helm's temple

            PATCH_IF zs_cons_add_basilisk_oil BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(1 2) STR_VAR item_name = ~zscsbsk0~ END // basilisk oil
            END

            PATCH_IF zs_cons_add_remedial_solution BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(3 7) STR_VAR item_name = ~zscsrms0~ END // remedial solution
            END

        BUT_ONLY
    END

    ACTION_IF FILE_EXISTS_IN_GAME ~dawnmas.sto~ BEGIN // DAWNMASTER's temple

        COPY_EXISTING ~dawnmas.sto~ ~override~ //dawnmaster's temple
                      ~temlath.sto~ ~override~ //lathander's temple

            PATCH_IF zs_cons_add_remedial_solution BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(3 7) STR_VAR item_name = ~zscsrms0~ END // remedial solution
            END

        BUT_ONLY

    END

    ACTION_IF FILE_EXISTS_IN_GAME ~trgeni01.sto~ BEGIN // trademeet genie

        COPY_EXISTING ~trgeni01.sto~ ~override~ //trademeet genie
                      ~trcar04.sto~ ~override~ // caravan merchant

            PATCH_IF zs_cons_add_angelic_reprieve BEGIN
                LPF resolve_amount INT_VAR chance=15 base_amount=2 target_amount = RANDOM(3 4) RET amount END
                LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
            END

            PATCH_IF zs_cons_add_angelic_slumber BEGIN
                LPF resolve_amount INT_VAR chance=4 base_amount=2 target_amount = 3 RET amount END
                LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsasl0~ END // angelic slumber
            END

        BUT_ONLY

    END

    ACTION_IF FILE_EXISTS_IN_GAME ~temsup.sto~ BEGIN // waukeen's temple

        COPY_EXISTING ~temsup.sto~   ~override~ //waukeen's temple
                      ~amcler02.sto~ ~override~ // waukeen's temple (tob)

            PATCH_IF zs_cons_add_angelic_reprieve BEGIN
                LPF resolve_amount INT_VAR chance=10 base_amount=2 target_amount = RANDOM(2 3) RET amount END
                LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
            END

            PATCH_IF zs_cons_add_remedial_solution BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(5 8) STR_VAR item_name = ~zscsrms0~ END // remedial solution
            END

        BUT_ONLY

    END

    ACTION_IF FILE_EXISTS_IN_GAME ~friend.sto~ BEGIN // friendly arm inn

        COPY_EXISTING ~friend.sto~ ~override~ // friendly arm inn

            PATCH_IF zs_cons_add_remedial_solution BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(2 3) STR_VAR item_name = ~zscsrms0~ END // remedial solution
            END

        BUT_ONLY
        
    END

    ACTION_IF FILE_EXISTS_IN_GAME ~ribald3.sto~ BEGIN // ribald's shop

        COPY_EXISTING ~ribald3.sto~ ~override~ // ribald's shop

            PATCH_IF zs_cons_add_angelic_reprieve BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(3 5) STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
            END

            PATCH_IF zs_cons_add_angelic_slumber BEGIN
                LPF resolve_amount INT_VAR chance=10 base_amount=2 target_amount = RANDOM(3 4) RET amount END
                LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsasl0~ END // angelic slumber
            END

        BUT_ONLY

    END

    ACTION_IF FILE_EXISTS_IN_GAME ~udduer02.sto~ BEGIN // duergar merchant (when encountered as a drow)
        COPY_EXISTING ~udduer02.sto~ ~override~ // duergar merchant (when encountered as a drow)

            PATCH_IF zs_cons_add_basilisk_oil BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(3 5) STR_VAR item_name = ~zscsbsk0~ END // basilisk oil
            END

            PATCH_IF zs_cons_add_remedial_solution BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(3 5) STR_VAR item_name = ~zscsrms0~ END // remedial solution
            END

        BUT_ONLY
    END

    ACTION_IF FILE_EXISTS_IN_GAME ~bdbeleg3.sto~ BEGIN // SOD QUARTERMASTER

        COPY_EXISTING ~bdbeleg3.sto~ ~override~ // sod quartermaster

            PATCH_IF zs_cons_add_angelic_reprieve BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(5 7) STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
            END

            PATCH_IF zs_cons_add_angelic_slumber BEGIN
                LPF resolve_amount INT_VAR chance=15 base_amount=2 target_amount = RANDOM(3 4) RET amount END
                LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsasl0~ END // angelic slumber
            END

            PATCH_IF zs_cons_add_basilisk_oil BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(10 12) STR_VAR item_name = ~zscsbsk0~ END // basilisk oil
            END

            PATCH_IF zs_cons_add_remedial_solution BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(10 15) STR_VAR item_name = ~zscsrms0~ END // remedial solution
            END

        BUT_ONLY

    END

    ACTION_IF FILE_EXISTS_IN_GAME ~bdnazram.sto~ BEGIN // SOD GENIE

        COPY_EXISTING ~bdnazram.sto~ ~override~ // sod genie

            PATCH_IF zs_cons_add_angelic_reprieve BEGIN
                LPF resolve_amount INT_VAR chance=20 base_amount=1 target_amount = RANDOM(1 3) RET amount END
                LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
            END

            PATCH_IF zs_cons_add_angelic_slumber BEGIN
                LPF resolve_amount INT_VAR chance=15 base_amount=1 target_amount = RANDOM(1 2) RET amount END
                LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsasl0~ END // angelic slumber
            END

        BUT_ONLY

    END

    ACTION_IF FILE_EXISTS_IN_GAME ~bdsorcsc.sto~ BEGIN // SOD SORCEROUS SUNDRIES

        COPY_EXISTING ~bdsorcsc.sto~ ~override~ // sod sorcerous sundries

            PATCH_IF zs_cons_add_basilisk_oil BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(5 8) STR_VAR item_name = ~zscsbsk0~ END // basilisk oil
            END

        BUT_ONLY

    END

    ACTION_IF FILE_EXISTS_IN_GAME ~highhedg.sto~ BEGIN // HIGH HEDGE

        COPY_EXISTING ~highhedg.sto~ ~override~ // high hedge
                      ~sto0703.sto~  ~override~ // sorcerous sundries

            PATCH_IF zs_cons_add_basilisk_oil BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(5 10) STR_VAR item_name = ~zscsbsk0~ END // basilisk oil
            END

        BUT_ONLY

    END

    ACTION_IF FILE_EXISTS_IN_GAME ~inn3351.sto~ BEGIN // FELDEPOST INN

        COPY_EXISTING ~inn3351.sto~ ~override~ // FELDEPOST INN

            PATCH_IF zs_cons_add_remedial_solution BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(1 4) STR_VAR item_name = ~zscsrms0~ END // remedial solution
            END

        BUT_ONLY
        
    END

    ACTION_IF FILE_EXISTS_IN_GAME ~amsmug01.sto~ BEGIN // AMEKTHRAN SMUGGLERS
    
        COPY_EXISTING ~amsmug01.sto~ ~override~ // amekthran smugglers
                      ~amsmug02.sto~ ~override~ // amekthran smugglers

            PATCH_IF zs_cons_add_angelic_reprieve BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = 2 STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
            END

            PATCH_IF zs_cons_add_angelic_slumber BEGIN
                LPF resolve_amount INT_VAR chance=10 base_amount=1 target_amount = 2 RET amount END
                LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsasl0~ END // angelic slumber
            END

        BUT_ONLY

    END

    ACTION_IF FILE_EXISTS_IN_GAME ~hgkar01.sto~ BEGIN // Karthis al-Hezzar

        COPY_EXISTING ~hgkar01.sto~  ~override~ // Karthis al-Hezzar

            PATCH_IF zs_cons_add_angelic_reprieve BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(6 7) STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
            END

            PATCH_IF zs_cons_add_angelic_slumber BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(3 4) STR_VAR item_name = ~zscsasl0~ END // angelic slumber
            END

            PATCH_IF zs_cons_add_basilisk_oil BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(8 12) STR_VAR item_name = ~zscsbsk0~ END // basilisk oil
            END

            PATCH_IF zs_cons_add_remedial_solution BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(16 24) STR_VAR item_name = ~zscsrms0~ END // remedial solution
            END

        BUT_ONLY
        
    END


    ACTION_IF FILE_EXISTS_IN_GAME ~ohnpotme.sto~ BEGIN // POTION MERCHANT (NEERA'S QUEST)

        COPY_EXISTING ~ohnpotme.sto~ ~override~ // POTION MERCHANT (NEERA'S QUEST)

            PATCH_IF zs_cons_add_basilisk_oil BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(3 5) STR_VAR item_name = ~zscsbsk0~ END // basilisk oil
            END

        BUT_ONLY

    END

    ACTION_IF FILE_EXISTS_IN_GAME ~garlena.sto~ BEGIN // GARLENA (watcher's keep)

        COPY_EXISTING ~garlena.sto~ ~override~ // GARLENA (watcher's keep)

            PATCH_IF zs_cons_add_angelic_reprieve BEGIN
                LPF resolve_amount INT_VAR chance=25 base_amount=RANDOM(7 9) target_amount = RANDOM(9 12) RET amount END
                LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
            END

            PATCH_IF zs_cons_add_angelic_slumber BEGIN
                LPF resolve_amount INT_VAR chance=10 base_amount=RANDOM(4 5) target_amount = RANDOM(5 7) RET amount END
                LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsasl0~ END // angelic slumber
            END

            PATCH_IF zs_cons_add_basilisk_oil BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(16 24) STR_VAR item_name = ~zscsbsk0~ END // basilisk oil
            END

            PATCH_IF zs_cons_add_remedial_solution BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(20 30) STR_VAR item_name = ~zscsrms0~ END // remedial solution
            END

        BUT_ONLY

    END

    ACTION_IF FILE_EXISTS_IN_GAME ~suelf10.sto~ BEGIN // SULDANESSELAR MERCHANT

        COPY_EXISTING ~suelf10.sto~ ~override~ // SULDANESSELAR MERCHANT

            PATCH_IF zs_cons_add_angelic_reprieve BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(3 4) STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
            END
            
            PATCH_IF zs_cons_add_angelic_slumber BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(1 2) STR_VAR item_name = ~zscsasl0~ END // angelic slumber
            END

        BUT_ONLY

    END

    ACTION_IF FILE_EXISTS_IN_GAME ~tem2304.sto~ BEGIN // gellana mirrorshade

        COPY_EXISTING ~tem2304.sto~ ~override~ // gellana mirrorshade

            PATCH_IF zs_cons_add_angelic_reprieve BEGIN
                LPF resolve_amount INT_VAR chance=15 RET amount END
                LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
            END

            PATCH_IF zs_cons_add_remedial_solution BEGIN
                LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(4 6) STR_VAR item_name = ~zscsrms0~ END // remedial solution
            END

        BUT_ONLY

    END

END ELSE BEGIN

    COPY_EXISTING ~kuork0.sto~ ~override~ // orrick IWDEE

        PATCH_IF zs_cons_add_angelic_reprieve BEGIN
            LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(4 6) STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
        END

        PATCH_IF zs_cons_add_angelic_slumber BEGIN
            LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(3 4) STR_VAR item_name = ~zscsasl0~ END // angelic slumber
        END

        PATCH_IF zs_cons_add_basilisk_oil BEGIN
            LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM (7 10) STR_VAR item_name = ~zscsbsk0~ END // basilisk oil
        END 

    BUT_ONLY IF_EXISTS

    COPY_EXISTING ~edion.sto~ ~override~ // edion IWDEE

        PATCH_IF zs_cons_add_angelic_reprieve BEGIN
            LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(2 4) STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
        END

        PATCH_IF zs_cons_add_angelic_slumber BEGIN
            LPF resolve_amount INT_VAR chance=15 RET amount END
            LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsasl0~ END // angelic slumber
        END

        PATCH_IF zs_cons_add_basilisk_oil BEGIN
            LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(3 8) STR_VAR item_name = ~zscsbsk0~ END // basilisk oil
        END

    BUT_ONLY IF_EXISTS

    COPY_EXISTING ~shlehlan.sto~ ~override~ // severed hand ghost merchant iwdee

        PATCH_IF zs_cons_add_angelic_reprieve BEGIN
            LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(3 4) STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
        END

        PATCH_IF zs_cons_add_angelic_slumber BEGIN
            LPF resolve_amount INT_VAR chance=15 RET amount END
            LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsasl0~ END // angelic slumber
        END

        PATCH_IF zs_cons_add_remedial_solution BEGIN
            LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(5 8) STR_VAR item_name = ~zscsrms0~ END // remedial solution
        END

    BUT_ONLY IF_EXISTS

    COPY_EXISTING ~bandoth.sto~ ~override~ // orrick IWDEE

        PATCH_IF zs_cons_add_basilisk_oil BEGIN
            LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(5 10) STR_VAR item_name = ~zscsbsk0~ END // basilisk oil
        END

    BUT_ONLY IF_EXISTS

    COPY_EXISTING ~ldd_nym.sto~ ~override~ // severed hand ghost merchant iwdee

        PATCH_IF zs_cons_add_basilisk_oil BEGIN
            LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(5 10) STR_VAR item_name = ~zscsbsk0~ END // basilisk oil
        END

        PATCH_IF zs_cons_add_remedial_solution BEGIN
            LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(4 6) STR_VAR item_name = ~zscsrms0~ END // remedial solution
        END

        PATCH_IF zs_cons_add_angelic_reprieve BEGIN
            LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(3 5) STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
        END

        PATCH_IF zs_cons_add_angelic_slumber BEGIN
            LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(1 3) STR_VAR item_name = ~zscsasl0~ END // angelic slumber
        END

    BUT_ONLY IF_EXISTS

    COPY_EXISTING ~waukeen.sto~ ~override~ // severed hand ghost merchant iwdee

        PATCH_IF zs_cons_add_basilisk_oil BEGIN
            LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(5 14) STR_VAR item_name = ~zscsbsk0~ END // basilisk oil
        END

        PATCH_IF zs_cons_add_remedial_solution BEGIN
            LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(10 16) STR_VAR item_name = ~zscsrms0~ END // remedial solution
        END

        PATCH_IF zs_cons_add_angelic_reprieve BEGIN
            LPF ADD_STORE_ITEM_EX INT_VAR stack = RANDOM(5 8) STR_VAR item_name = ~zscsarp0~ END // angelic reprieve
        END

        PATCH_IF zs_cons_add_angelic_slumber BEGIN
            LPF resolve_amount INT_VAR chance=15 base_amount=3 target_amount = RANDOM(4 5) RET amount END
            LPF ADD_STORE_ITEM_EX INT_VAR stack = amount STR_VAR item_name = ~zscsasl0~ END // angelic slumber
        END

    BUT_ONLY IF_EXISTS

END