INCLUDE ~%MOD_FOLDER%/libs/scripts/potions/fragments/zs_incl_potions.tph~

PRINT "[INFO]: Distributing potions to stores and NPCs..."
SILENT

INCLUDE ~%MOD_FOLDER%/libs/scripts/potions/fragments/zs_incl_potions_stores.tph~
INCLUDE ~%MOD_FOLDER%/libs/scripts/potions/fragments/zs_incl_potions_cre_manual.tph~
INCLUDE ~%MOD_FOLDER%/libs/scripts/potions/fragments/zs_incl_potions_cre_auto.tph~

VERBOSE
PRINT "[INFO]: Finished distributing remedies to NPCs and stores."