COPY_EXISTING ~ohbconco.sto~  ~override~ //bellowgup

    PATCH_IF !VARIABLE_IS_SET "zs_cons_pod_add_arcane" BEGIN
        PATCH_IF FILE_EXISTS_IN_GAME ~zscsmd01.itm~ BEGIN
            ADD_STORE_ITEM ~zscsmd01~ #1 #0 #0 ~identified~ (15)
        END
    END ELSE PATCH_IF zs_cons_pod_add_arcane BEGIN
        ADD_STORE_ITEM ~zscsmd01~ #1 #0 #0 ~identified~ (zs_cons_pod_arcane_store)
    END

    PATCH_IF !VARIABLE_IS_SET "zs_cons_pod_add_caustic" BEGIN
        PATCH_IF FILE_EXISTS_IN_GAME ~zscsac01.itm~ BEGIN
            ADD_STORE_ITEM ~zscsac01~ #1 #0 #0 ~identified~ (20)
        END
    END ELSE PATCH_IF zs_cons_pod_add_caustic BEGIN
        ADD_STORE_ITEM ~zscsac01~ #1 #0 #0 ~identified~ (zs_cons_pod_caustic_store)
    END

    PATCH_IF !VARIABLE_IS_SET "zs_cons_pod_add_gelid" BEGIN
        PATCH_IF FILE_EXISTS_IN_GAME ~zscscd01.itm~ BEGIN
            ADD_STORE_ITEM ~zscscd01~ #1 #0 #0 ~identified~ (20)
        END
    END ELSE PATCH_IF zs_cons_pod_add_gelid BEGIN
        ADD_STORE_ITEM ~zscscd01~ #1 #0 #0 ~identified~ (zs_cons_pod_gelid_store)
    END

    PATCH_IF !VARIABLE_IS_SET "zs_cons_pod_add_scintillating" BEGIN
        PATCH_IF FILE_EXISTS_IN_GAME ~zscsel01.itm~ BEGIN
            ADD_STORE_ITEM ~zscsel01~ #1 #0 #0 ~identified~ (20)
        END
    END ELSE PATCH_IF zs_cons_pod_add_scintillating BEGIN
        ADD_STORE_ITEM ~zscsel01~ #1 #0 #0 ~identified~ (zs_cons_pod_scintillating_store)
    END

    PATCH_IF !VARIABLE_IS_SET "zs_cons_pod_add_igneous" BEGIN
        PATCH_IF FILE_EXISTS_IN_GAME ~zscsfr01.itm~ BEGIN
            ADD_STORE_ITEM ~zscsfr01~ #1 #0 #0 ~identified~ (20)
        END
    END ELSE PATCH_IF zs_cons_pod_add_igneous BEGIN
        ADD_STORE_ITEM ~zscsfr01~ #1 #0 #0 ~identified~ (zs_cons_pod_igneous_store)
    END

    PATCH_IF !VARIABLE_IS_SET "zs_cons_pod_add_noxious" BEGIN
        PATCH_IF FILE_EXISTS_IN_GAME ~zscsps01.itm~ BEGIN
            ADD_STORE_ITEM ~zscsps01~ #1 #0 #0 ~identified~ (15)
        END
    END ELSE PATCH_IF zs_cons_pod_add_noxious BEGIN
        ADD_STORE_ITEM ~zscsps01~ #1 #0 #0 ~identified~ (zs_cons_pod_noxious_store)
    END

    PATCH_IF !VARIABLE_IS_SET "zs_cons_pod_add_soporific" BEGIN
        PATCH_IF FILE_EXISTS_IN_GAME ~zscsps02.itm~ BEGIN
            ADD_STORE_ITEM ~zscsps02~ #1 #0 #0 ~identified~ (10)
        END
    END ELSE PATCH_IF zs_cons_pod_add_soporific BEGIN
        ADD_STORE_ITEM ~zscsps02~ #1 #0 #0 ~identified~ (zs_cons_pod_soporific_store)
    END

    PATCH_IF !VARIABLE_IS_SET "zs_cons_pod_add_kuotoa" BEGIN
        PATCH_IF FILE_EXISTS_IN_GAME ~zscsps05.itm~ BEGIN
            ADD_STORE_ITEM ~zscsps05~ #1 #0 #0 ~identified~ (3)
        END
    END ELSE PATCH_IF zs_cons_pod_add_kuotoa BEGIN
        ADD_STORE_ITEM ~zscsps05~ #1 #0 #0 ~identified~ (zs_cons_pod_kuotoa_store)
    END

    PATCH_IF !VARIABLE_IS_SET "zs_cons_pod_add_dragonbane" BEGIN
        PATCH_IF FILE_EXISTS_IN_GAME ~zscsps04.itm~ BEGIN
            ADD_STORE_ITEM ~zscsps04~ #1 #0 #0 ~identified~ (3)
        END
    END ELSE PATCH_IF zs_cons_pod_add_dragonbane BEGIN
        ADD_STORE_ITEM ~zscsps04~ #1 #0 #0 ~identified~ (zs_cons_pod_dragonbane_store)
    END

    PATCH_IF !VARIABLE_IS_SET "zs_cons_pod_add_dragonbile" BEGIN
        PATCH_IF FILE_EXISTS_IN_GAME ~zscsps03.itm~ BEGIN
            ADD_STORE_ITEM ~zscsps03~ #1 #0 #0 ~identified~ (6)
        END
    END ELSE PATCH_IF zs_cons_pod_add_dragonbile BEGIN
        ADD_STORE_ITEM ~zscsps03~ #1 #0 #0 ~identified~ (zs_cons_pod_dragonbile_store)
    END

    PATCH_IF !VARIABLE_IS_SET "zs_cons_pod_add_sanctified" BEGIN
        PATCH_IF FILE_EXISTS_IN_GAME ~zscshl01.itm~ BEGIN
            ADD_STORE_ITEM ~zscshl01~ #1 #0 #0 ~identified~ (8)
        END
    END ELSE PATCH_IF zs_cons_pod_add_sanctified BEGIN
        ADD_STORE_ITEM ~zscshl01~ #1 #0 #0 ~identified~ (zs_cons_pod_sanctified_store)
    END

    PATCH_IF !VARIABLE_IS_SET "zs_cons_pod_add_profane" BEGIN
        PATCH_IF FILE_EXISTS_IN_GAME ~zscsul01.itm~ BEGIN
            ADD_STORE_ITEM ~zscsul01~ #1 #0 #0 ~identified~ (8)
        END
    END ELSE PATCH_IF zs_cons_pod_add_profane BEGIN
        ADD_STORE_ITEM ~zscsul01~ #1 #0 #0 ~identified~ (zs_cons_pod_profane_store)
    END
