INCLUDE ~%MOD_FOLDER%/libs/scripts/elixirs/fragments/zs_incl_elixirs.tph~

PRINT "Distributing elixirs to stores and NPCs (no NPCs for now)..."
SILENT

INCLUDE ~%MOD_FOLDER%/libs/scripts/elixirs/fragments/zs_incl_elixirs_stores.tph~
INCLUDE ~%MOD_FOLDER%/libs/scripts/elixirs/fragments/zs_incl_elixirs_cre_manual.tph~
INCLUDE ~%MOD_FOLDER%/libs/scripts/elixirs/fragments/zs_incl_elixirs_cre_auto.tph~

VERBOSE
