INCLUDE ~%MOD_FOLDER%/libs/scripts/throwables/fragments/zs_incl_throwables.tph~

PRINT "Distributing throwables to NPCs and stores..."
SILENT

INCLUDE ~%MOD_FOLDER%/libs/scripts/throwables/fragments/zs_incl_throwables_stores.tph~
INCLUDE ~%MOD_FOLDER%/libs/scripts/throwables/fragments/zs_incl_throwables_cre_manual.tph~
INCLUDE ~%MOD_FOLDER%/libs/scripts/throwables/fragments/zs_incl_throwables_cre_auto.tph~

VERBOSE
PRINT "Finished distributing throwables to NPCs and stores."
